[project]
authors = [{ name = "Ivar Jönsson", email = "ivajns-9@student.ltu.se" }]
name = "flask_require"
version = "0.0.2"
description = "A simple Flask extension for requiring parameters in a request."
readme = "README.md"

[dependencies]
flask = ">=0.10.1"
